spring.application.name=warehouse
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
jwt.secret=my-super-secret-key-my-super-secret-key